- name: "Install octave environment"
  hosts:
    - "group_puhti"
    - "group_mahti"
  become: false

  tasks:
    - name: "Create directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "{{ appl_dir }}/octave"
        - "{{ appl_dir }}/octave/{{ version }}"
        - "{{ appl_dir }}/octave/{{ version }}/bin"
        - "{{ modulefiles_dir }}/octave"

    - name: "Copy files"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        group: "{{ group }}"
      loop:
        - src: "{{ playbook_dir }}/version/{{ version }}/bin/octave_apptainer_exec"
          dest: "{{ appl_dir }}/octave/{{ version }}/bin/octave_apptainer_exec"
          mode: "ug=rwx,o=rx"
        - src: "{{ playbook_dir }}/version/{{ version }}/bin/octave"
          dest: "{{ appl_dir }}/octave/{{ version }}/bin/octave"
          mode: "ug=rwx,o=rx"
        - src: "{{ playbook_dir }}/version/{{ version }}/Makefile"
          dest: "{{ appl_dir }}/octave/{{ version }}/Makefile"
          mode: "ug=rw,o=r"
        - src: "{{ playbook_dir }}/version/{{ version }}/octave.def"
          dest: "{{ appl_dir }}/octave/{{ version }}/octave.def"
          mode: "ug=rw,o=r"
        - src: "{{ playbook_dir }}/version/{{ version }}/octave.lua"
          dest: "{{ modulefiles_dir }}/octave/{{ version }}.lua"
          mode: "ug=rw,o=r"

    - name: "Build the container"
      ansible.builtin.command: |
        make
      args:
        chdir: "{{ appl_dir }}/octave/{{ version }}"
        creates: "{{ appl_dir }}/octave/{{ version }}/octave.sif"

    - name: "Set container mode"
      ansible.builtin.file:
        path: "{{ appl_dir }}/octave/{{ version }}/octave.sif"
        mode: "ug=rwx,o=rx"
